# Generated by Django 5.2.17 on 2026-09-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_rating_lock_and_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
